server:
  port: 8112

spring:
  application:
    name: mycloud-rabbitmq-consumer2

  # 数据源配置
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/my_cloud_test?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      max-active: 100
      min-idle: 10
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000


  # rabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: true
    # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: true
    # 服务注册到eureka服务的主机地址
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

# 异步线程池配置
task:
  pool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
    queueCapacity: 1000
