server.port=8080
#实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
eureka.client.register-with-eureka=false
#此客户端是否获取eureka服务器注册表上的注册信息，默认为true
eureka.client.fetch-registry=false
#服务注册到eureka时的地址
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

