server.port=8082
spring.application.name=provider
#解决错误 com.netflix.client.ClientException: Load balancer does not have available server for client:panfeng-item-service
#开启eureka负载均衡策略
ribbon.eureka.enabled=true
#服务注册到eureka服务端的主机地址
eureka.client.service-url.defaultZone=http://localhost:8080/eureka
