server:
  port: 8089

spring:
  application:
    name: mydubbo-consumer

  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      remove-abandoned: true
      remove-abandoned-timeout: 10000
      log-abandoned: true
      max-active: 10
      min-idle: 2
      initial-size: 2
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000


dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer  #应用名称
    owner: songdada       #应用所属者
    organization: songdada   #应用所属组织
  registry:
    id: zookeeper-registry #注册中心id
    protocol: zookeeper    #注册中心协议
    address: zookeeper://127.0.0.1:2181 #注册中心地址
#  monitor:
#    protocol: registry # 注册监控中心
  scan:
    base-packages: com.example.dubbo.consumer.service

service:
  version: 1.0.0

# thread pool
thread:
  pool:
    corePoolSize: 2
    maximumPoolSize: 5
    keepAliveTime: 100
    capacity: 5